openapi: 3.0.1
info:
  description: "## Overview\nThese usage endpoints define the following operations:\n\
    * **Usage**: Retrieve usage data for the specified time period (default is one\
    \ month).\n    \n    * Users must have the `View Billing` permission to access\
    \ this endpoint.\n    * This endpoint offers visibility across all account groups\
    \ within the organization.\n    * Users with `View Billing` permission in multiple\
    \ organizations should query the endpoint with the `aid` query string parameter\
    \ (see optional parameters) for each organization.\n\n* **Quotas**: Obtain organization\
    \ and account usage quotas. Additionally, users with the appropriate permissions\
    \ can create, update, or delete these quotas.\n    \n    * Users must have the\
    \ necessary permissions to perform quota-related actions.\n\nRefer to the API\
    \ definitions below for detailed usage instructions and optional parameters."
  title: Usage API
  version: 7.0.0
externalDocs:
  description: Find out more about the usage model
  url: https://docs.thousandeyes.com/product-documentation/user-management/usage-and-billing/how-unit-consumption-works#what-is-the-projected-usage
servers:
- description: Thousandeyes API production URL
  url: https://api.thousandeyes.com
security:
- BearerAuth:
  - read
tags:
- description: Usage GET Operation
  name: Usage
- description: Quota CRUD Operation
  name: Quotas
paths:
  /v7/usage:
    get:
      description: "This endpoint returns the organization's usage data for a specified\
        \ time period. If no time period is specified, it defaults to the last month.\
        \   "
      operationId: getUsage
      parameters:
      - description: A unique identifier associated with your account group. You can
          retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note
          that you must be assigned to the target account group. Specifying this parameter
          without being assigned to the target account group will result in an error
          response.
        in: query
        name: aid
        required: false
        schema:
          example: "2067"
          type: string
      - description: "Expands the available resources. By default, no expansion takes\
          \ place if the  `expand` query parameter is not passed. For example, to\
          \ expand the \"tests\"  resource, pass the query '?expand=test'."
        explode: false
        in: query
        name: expand
        required: false
        schema:
          example:
          - test
          items:
            $ref: '#/components/schemas/Expand'
          type: array
        style: form
      responses:
        "200":
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/getUsage_200_response'
          description: OK
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Get usage information for the last month
      tags:
      - Usage
      x-accepts: "application/hal+json,application/problem+json"
  /v7/quotas:
    get:
      description: "This endpoint retrieves usage quotas for both organization and\
        \ account groups. To use this endpoint, you need the `Edit organization and\
        \ account group quotas` permission, which is a management-level permission.\
        \ If a user has quota update permission in multiple organizations, the API\
        \ returns data from all such organizations."
      operationId: getQuotas
      responses:
        "200":
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/getQuotas_200_response'
          description: OK
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Get organization and account group usage quota
      tags:
      - Quotas
      x-accepts: "application/hal+json,application/problem+json"
  /v7/quotas/assign:
    post:
      description: "This endpoint recieves a list of organization quotas to create\
        \ or update. If there's no specific `orgId` defined for a quota, it defaults\
        \ to using the authenticated organization. To use this endpoint, you need\
        \ the `Edit organization and account group quotas` permission, which is a\
        \ management-level permission. This endpoint follows cumulative behavior––\
        This means that the quotas are assigned to the specified organizations, and\
        \ any previous assignments remain unchanged; no unassignments occur."
      operationId: assignOrganizationsQuotas
      parameters:
      - description: A unique identifier associated with your account group. You can
          retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note
          that you must be assigned to the target account group. Specifying this parameter
          without being assigned to the target account group will result in an error
          response.
        in: query
        name: aid
        required: false
        schema:
          example: "2067"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuotasAssignRequest'
      responses:
        "201":
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/QuotasAssignResponse'
          description: Created
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Create or update organizations quotas
      tags:
      - Quotas
      x-content-type: application/json
      x-accepts: "application/hal+json,application/problem+json"
  /v7/quotas/unassign:
    post:
      description: "This endpoint recieves a list of organization IDs to remove their\
        \ current quota. To use this endpoint, you need the `Edit organization and\
        \ account group quotas` permission, which is a management-level permission."
      operationId: unassignOrganizationsQuotas
      parameters:
      - description: A unique identifier associated with your account group. You can
          retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note
          that you must be assigned to the target account group. Specifying this parameter
          without being assigned to the target account group will result in an error
          response.
        in: query
        name: aid
        required: false
        schema:
          example: "2067"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuotasUnassign'
      responses:
        "204":
          content:
            application/json: {}
          description: No content
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Remove organization quotas
      tags:
      - Quotas
      x-content-type: application/json
      x-accepts: application/json
  /v7/quotas/account-groups/assign:
    post:
      description: |-
        Assigns quota values to multiple account groups from multiple organizations. `Edit organization and account group quotas` permission (a management permission) is required. This endpoint has cumulative behavior: The quotas are assigned to the specified account groups, and the previous assignments persist. No unassignment takes place.

        This endpoint assigns quota values to multiple account groups across multiple organizations. To use this endpoint, you need the `Edit organization and account group quotas` permission, which is a management-level permission. This endpoint follows a cumulative behavior––This means that the quotas are assigned to the designated account groups, and any previous assignments remain in place without any unassignment occurring.
      operationId: assignOrganizationsAccountGroupsQuotas
      parameters:
      - description: A unique identifier associated with your account group. You can
          retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note
          that you must be assigned to the target account group. Specifying this parameter
          without being assigned to the target account group will result in an error
          response.
        in: query
        name: aid
        required: false
        schema:
          example: "2067"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationsQuotasAssign'
      responses:
        "201":
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/OrganizationsQuotasAssign'
          description: Created
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Create or update accout group quotas
      tags:
      - Quotas
      x-content-type: application/json
      x-accepts: "application/hal+json,application/problem+json"
  /v7/quotas/account-groups/unassign:
    post:
      description: "Removes the quotas from multiple account groups from multiple\
        \ organizations. `Edit organization and account group quotas` permission (a\
        \ management permission) is required. Removes quotas from multiple account\
        \ groups across multiple organizations. To use this endpoint, you need the\
        \ `Edit organization and account group quotas` permission, which is a management-level\
        \ permission."
      operationId: unassignOrganizationsAccountGroupsQuotas
      parameters:
      - description: A unique identifier associated with your account group. You can
          retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note
          that you must be assigned to the target account group. Specifying this parameter
          without being assigned to the target account group will result in an error
          response.
        in: query
        name: aid
        required: false
        schema:
          example: "2067"
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationsQuotasUnassign'
      responses:
        "204":
          content:
            application/json: {}
          description: No content
        "400":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Request validation failed. There are invalid or missing fields
                status: 400
                detail: Invalid field value for field `expand`
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Insufficient permissions to query endpoint
        "404":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: URI Resource Not Found
                status: 404
                detail: Details explaining if the 404 error is related to an invalid
                  URI or a wrong ID
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Not found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Exhausted rate limit for the organization
        "500":
          content:
            application/problem+json:
              example:
                type: about:blank
                title: Internal server error
                status: 500
                detail: Optional detail about the internal error message.
                instance: /v7
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal server error
      summary: Remove account group quotas from organizations
      tags:
      - Quotas
      x-content-type: application/json
      x-accepts: application/json
components:
  parameters:
    ExpandUsage:
      description: "Expands the available resources. By default, no expansion takes\
        \ place if the  `expand` query parameter is not passed. For example, to expand\
        \ the \"tests\"  resource, pass the query '?expand=test'."
      explode: false
      in: query
      name: expand
      required: false
      schema:
        example:
        - test
        items:
          $ref: '#/components/schemas/Expand'
        type: array
      style: form
    AccountGroupId:
      description: A unique identifier associated with your account group. You can
        retrieve your `AccountGroupId` from the `/account-groups` endpoint. Note that
        you must be assigned to the target account group. Specifying this parameter
        without being assigned to the target account group will result in an error
        response.
      in: query
      name: aid
      required: false
      schema:
        example: "2067"
        type: string
  responses:
    "400":
      content:
        application/problem+json:
          example:
            type: about:blank
            title: Request validation failed. There are invalid or missing fields
            status: 400
            detail: Invalid field value for field `expand`
            instance: /v7
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad Request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Insufficient permissions to query endpoint
    "404":
      content:
        application/problem+json:
          example:
            type: about:blank
            title: URI Resource Not Found
            status: 404
            detail: Details explaining if the 404 error is related to an invalid URI
              or a wrong ID
            instance: /v7
          schema:
            $ref: '#/components/schemas/Error'
      description: Not found
    "429":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Exhausted rate limit for the organization
    "500":
      content:
        application/problem+json:
          example:
            type: about:blank
            title: Internal server error
            status: 500
            detail: Optional detail about the internal error message.
            instance: /v7
          schema:
            $ref: '#/components/schemas/Error'
      description: Internal server error
    "204":
      content:
        application/json: {}
      description: No content
  schemas:
    Expand:
      enum:
      - test
      - enterprise-agent
      - enterprise-agent-unit
      - endpoint-agent
      - endpoint-agent-essential
      - endpoint-agent-embedded
      type: string
    OrganizationQuota:
      properties:
        value:
          description: Value of the quota for the given Organization.
          example: 22500
          format: int64
          type: integer
        orgId:
          description: Unique ID of the organization.
          example: "10"
          type: string
      required:
      - value
      type: object
    AccountGroupQuota:
      example:
        value: 12000
        aid: "35"
      properties:
        value:
          description: Value of the quota for the given Account Group.
          example: 12000
          format: int64
          type: integer
        aid:
          description: Unique ID of the account group.
          example: "35"
          type: string
      type: object
    Quotas:
      properties:
        quotas:
          items:
            $ref: '#/components/schemas/Quotas_quotas_inner'
          type: array
      type: object
    Usage:
      properties:
        usage:
          $ref: '#/components/schemas/Usage_usage'
      type: object
    EnterpriseAgents:
      description: Enterprise agents used by account group.
      example:
      - aid: "7625"
        accountGroupName: Support
        enterpriseAgentsUsed: 7
      - aid: "315"
        accountGroupName: Documentation
        enterpriseAgentsUsed: 1
      items:
        $ref: '#/components/schemas/EnterpriseAgents_inner'
      type: array
    EnterpriseAgentUnits:
      description: A breakdown of enterprise unit consumption for each agent during
        the current monthly period. Each entry provides data for both the current
        actual usage and the projected usage. Returns non-zero values for organizations
        with metered billing.
      items:
        $ref: '#/components/schemas/EnterpriseAgentUnits_inner'
      type: array
    Tests:
      description: A breakdown of unit consumption for each test during the current
        monthly period. Each entry provides information about both the current actual
        usage and the projected usage.
      example:
      - aid: "315"
        testId: "1158"
        accountGroupName: Documentation
        testName: https://app.thousandeyes.com
        testType: Web-Page Load
        cloudUnitsUsed: 14050
        cloudUnitsProjected: 340674
      - aid: "315"
        testId: "1159"
        accountGroupName: Documentation
        testName: https://support.thousandeyes.com
        testType: Web - HTTP Server
        cloudUnitsUsed: 64390
        cloudUnitsProjected: 164457
      items:
        $ref: '#/components/schemas/Tests_inner'
      type: array
    EndpointAgents:
      description: Endpoint agents used by account group.
      example:
      - aid: "7625"
        accountGroupName: Support
        endpointAgentsUsed: 22
      - aid: "315"
        accountGroupName: Documentation
        endpointAgentsUsed: 14
      items:
        $ref: '#/components/schemas/EndpointAgents_inner'
      type: array
    EndpointAgentsEssentials:
      description: Endpoint agents essentials used by account group.
      example:
      - aid: "10"
        accountGroupName: Support
        endpointAgentsEssentialsUsed: 2
      - aid: "100"
        accountGroupName: Documentation
        endpointAgentsEssentialsUsed: 3
      items:
        $ref: '#/components/schemas/EndpointAgentsEssentials_inner'
      type: array
    EndpointAgentsEmbedded:
      description: Endpoint agents embedded used by account group.
      example:
      - aid: "10"
        accountGroupName: Support
        endpointAgentsEmbeddedUsed: 2
      - aid: "100"
        accountGroupName: Documentation
        endpointAgentsEmbeddedUsed: 3
      items:
        $ref: '#/components/schemas/EndpointAgentsEmbedded_inner'
      type: array
    QuotasAssignRequest:
      example:
        organizations:
        - value: 12000
        - orgId: "315"
          value: 10000
      properties:
        organizations:
          example:
          - value: 12000
          - orgId: "315"
            value: 10000
          items:
            $ref: '#/components/schemas/OrganizationQuota'
          type: array
      type: object
    QuotasAssignResponse:
      properties:
        organizations:
          example:
          - orgId: "100"
            value: 12000
          - orgId: "315"
            value: 10000
          items:
            $ref: '#/components/schemas/OrganizationQuota'
          type: array
      type: object
    QuotasUnassign:
      example:
        organizations:
        - "100"
        - "315"
      properties:
        organizations:
          example:
          - "100"
          - "315"
          items:
            type: string
          type: array
      type: object
    OrganizationsQuotasAssign:
      example:
        organizations:
        - orgId: "315"
          accountGroups:
          - value: 12000
            aid: "35"
          - value: 12000
            aid: "35"
        - orgId: "315"
          accountGroups:
          - value: 12000
            aid: "35"
          - value: 12000
            aid: "35"
      properties:
        organizations:
          items:
            $ref: '#/components/schemas/OrganizationsQuotasAssign_organizations_inner'
          type: array
      type: object
    OrganizationsQuotasUnassign:
      example:
        organizations:
        - orgId: "315"
          accountGroups:
          - "35"
          - "720"
        - orgId: "315"
          accountGroups:
          - "35"
          - "720"
      properties:
        organizations:
          items:
            $ref: '#/components/schemas/OrganizationsQuotasUnassign_organizations_inner'
          type: array
      type: object
    AccountGroupIds:
      description: List of account group IDs.
      example:
      - "35"
      - "720"
      items:
        type: string
      type: array
    SelfLinks:
      properties:
        _links:
          $ref: '#/components/schemas/SelfLinks__links'
      readOnly: true
      type: object
    Link:
      description: A hyperlink from the containing resource to a URI.
      properties:
        href:
          description: "Its value is either a URI [RFC3986] or a URI template [RFC6570]."
          example: https://api.thousandeyes.com/v7/link/to/resource/id
          type: string
        templated:
          description: Should be true when the link object's "href" property is a
            URI template.
          type: boolean
        type:
          description: Used as a hint to indicate the media type expected when dereferencing
            the target resource.
          type: string
        deprecation:
          description: Its presence indicates that the link is to be deprecated at
            a future date. Its value is a URL that should provide further information
            about the deprecation.
          type: string
        name:
          description: Its value may be used as a secondary key for selecting link
            objects that share the same relation type.
          type: string
        profile:
          description: A URI that hints about the profile of the target resource.
          type: string
        title:
          description: Intended for labelling the link with a human-readable identifier
          type: string
        hreflang:
          description: Indicates the language of the target resource
          type: string
      required:
      - href
      type: object
    Error:
      properties:
        type:
          description: "A URI reference that identifies the problem type. When this\
            \ member is not present, its value is assumed to be \"about:blank\"."
          type: string
        title:
          description: "A short, human-readable summary of the problem type."
          type: string
        status:
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: A URI reference that identifies the specific occurrence of
            the problem.
          type: string
      type: object
    UnauthorizedError:
      properties:
        error:
          example: invalid_token
          type: string
        error_description:
          example: Invalid access token
          type: string
      type: object
    AccountGroup:
      allOf:
      - $ref: '#/components/schemas/AccountGroupId'
      - properties:
          accountGroupName:
            description: Account group name
            example: Account A
            type: string
        type: object
      type: object
    AccountGroupId:
      properties:
        aid:
          description: A unique identifier associated with your account group. You
            can retrieve your `AccountGroupId` from the `/account-groups` endpoint.
          example: "11"
          type: string
      type: object
    getUsage_200_response:
      allOf:
      - $ref: '#/components/schemas/Usage'
      - $ref: '#/components/schemas/SelfLinks'
    getQuotas_200_response:
      allOf:
      - $ref: '#/components/schemas/Quotas'
      - $ref: '#/components/schemas/SelfLinks'
    Quotas_quotas_inner:
      properties:
        organizationQuota:
          $ref: '#/components/schemas/OrganizationQuota'
        accountGroupQuotas:
          example:
          - value: 12000
            aid: "315"
          - value: 10000
            aid: "1200"
          items:
            $ref: '#/components/schemas/AccountGroupQuota'
          type: array
      type: object
    Usage_usage_quota:
      properties:
        monthStart:
          description: Beginning of usage period in UTC (ISO date-time format).
          example: 2020-01-05T08:00:00Z
          format: date-time
          type: string
        monthEnd:
          description: End of usage period in UTC (ISO date-time format)..
          example: 2020-02-05T08:00:00Z
          format: date-time
          type: string
        cloudUnitsIncluded:
          description: "Monthly number of cloud units allocated, as part of the contract."
          example: 4320000000
          format: int64
          type: integer
        endpointAgentsIncluded:
          description: "Monthly number of endpoint agents allocated, as part of the\
            \ contract."
          example: 200
          format: int64
          type: integer
        endpointAgentsEssentialsIncluded:
          description: "Monthly number of endpoint agents essentials allocated, as\
            \ part of the contract."
          example: 10
          format: int64
          type: integer
        endpointAgentsEmbeddedIncluded:
          description: "Number of embedded endpoint agents allocated monthly, as specified\
            \ in the contract."
          example: 10
          format: int64
          type: integer
        enterpriseAgentsIncluded:
          description: "Monthly number of enterprise agents allocated, as part of\
            \ the contract. Returns non-zero value only for organizations with legacy\
            \ billing."
          example: 25
          format: int64
          type: integer
      type: object
    Usage_usage:
      properties:
        quota:
          $ref: '#/components/schemas/Usage_usage_quota'
        cloudUnitsUsed:
          description: Number of cloud units consumed thus far in the usage period.
          example: 8500489
          format: int64
          type: integer
        cloudUnitsProjected:
          description: "Number of cloud units projected in the current usage period,\
            \ based on units consumed to date and configuration of enabled tests.\
            \ This value is updated hourly."
          example: 20993812
          format: int64
          type: integer
        cloudUnitsNextBillingPeriod:
          description: "Number of cloud units projected in the upcoming usage period,\
            \ based on configuration of enabled tests. This value is updated hourly."
          example: 25123456
          format: int64
          type: integer
        enterpriseUnitsUsed:
          description: Number of enterprise units consumed in the usage period. Returns
            non-zero value only for organizations with metered billing.
          example: 79640902
          format: int64
          type: integer
        enterpriseUnitsProjected:
          description: "Number of enterprise units projected in the current usage\
            \ period, based on units consumed to date and configuration of enabled\
            \ tests. This value is updated hourly. Returns non-zero value only for\
            \ organizations with metered billing."
          example: 108016317
          format: int64
          type: integer
        enterpriseUnitsNextBillingPeriod:
          description: "Number of enterprise units projected in the upcoming usage\
            \ period, based on configuration of enabled tests. This value is updated\
            \ hourly. Returns non-zero value only for organizations with metered billing."
          example: 0
          format: int64
          type: integer
        endpointAgentsUsed:
          description: Number of endpoint agents used in the current usage period.
            This number is calculated by taking the maximum number of agents enabled
            for any one-hour period in the usage period. Disabled agents are excluded
            from this calculation.
          example: 42
          format: int64
          type: integer
        endpointAgentsEssentialsUsed:
          description: Number of endpoint agents essentials used in the current usage
            period. This number is calculated by taking the maximum number of agents
            enabled for any one-hour period in the usage period. Disabled agents are
            excluded from this calculation.
          example: 5
          format: int64
          type: integer
        endpointAgentsEmbeddedUsed:
          description: Number of embedded endpoint agents used in the current usage
            period. This number is calculated by taking the maximum number of agents
            enabled for any one-hour period in the usage period. Disabled agents are
            excluded from this calculation.
          example: 5
          format: int64
          type: integer
        enterpriseAgentsUsed:
          description: Number of enterprise agents used in the current usage period.
            This number is calculated by taking the maximum number of agents enabled
            for any one-hour period in the usage period. Disabled agents are excluded
            from this calculation.
          example: 58
          format: int64
          type: integer
        enterpriseAgentUnits:
          description: A breakdown of enterprise unit consumption for each agent during
            the current monthly period. Each entry provides data for both the current
            actual usage and the projected usage. Returns non-zero values for organizations
            with metered billing.
          items:
            $ref: '#/components/schemas/EnterpriseAgentUnits_inner'
          type: array
        tests:
          description: A breakdown of unit consumption for each test during the current
            monthly period. Each entry provides information about both the current
            actual usage and the projected usage.
          example:
          - aid: "315"
            testId: "1158"
            accountGroupName: Documentation
            testName: https://app.thousandeyes.com
            testType: Web-Page Load
            cloudUnitsUsed: 14050
            cloudUnitsProjected: 340674
          - aid: "315"
            testId: "1159"
            accountGroupName: Documentation
            testName: https://support.thousandeyes.com
            testType: Web - HTTP Server
            cloudUnitsUsed: 64390
            cloudUnitsProjected: 164457
          items:
            $ref: '#/components/schemas/Tests_inner'
          type: array
        endpointAgents:
          description: Endpoint agents used by account group.
          example:
          - aid: "7625"
            accountGroupName: Support
            endpointAgentsUsed: 22
          - aid: "315"
            accountGroupName: Documentation
            endpointAgentsUsed: 14
          items:
            $ref: '#/components/schemas/EndpointAgents_inner'
          type: array
        endpointAgentsEssentials:
          description: Endpoint agents essentials used by account group.
          example:
          - aid: "10"
            accountGroupName: Support
            endpointAgentsEssentialsUsed: 2
          - aid: "100"
            accountGroupName: Documentation
            endpointAgentsEssentialsUsed: 3
          items:
            $ref: '#/components/schemas/EndpointAgentsEssentials_inner'
          type: array
        endpointAgentsEmbedded:
          description: Endpoint agents embedded used by account group.
          example:
          - aid: "10"
            accountGroupName: Support
            endpointAgentsEmbeddedUsed: 2
          - aid: "100"
            accountGroupName: Documentation
            endpointAgentsEmbeddedUsed: 3
          items:
            $ref: '#/components/schemas/EndpointAgentsEmbedded_inner'
          type: array
        enterpriseAgents:
          description: Enterprise agents used by account group.
          example:
          - aid: "7625"
            accountGroupName: Support
            enterpriseAgentsUsed: 7
          - aid: "315"
            accountGroupName: Documentation
            enterpriseAgentsUsed: 1
          items:
            $ref: '#/components/schemas/EnterpriseAgents_inner'
          type: array
      type: object
    EnterpriseAgents_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: A unique identifier that specifies the account group that
              owns the enterprise agents.
          accountGroupName:
            description: Name of the account group which owns the enterprise agents.
          enterpriseAgentsUsed:
            description: Number of enterprise agents owned by the specific account
              group in the usage period.
            format: int64
            type: integer
        type: object
    EnterpriseAgentUnits_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: Unique identifier of the account group owning the enterprise
              agent units.
          accountGroupName:
            description: Name of the account group which owns the enterprise agent
              units.
          agentId:
            description: Unique identifier of the enterprise agent generating usage.
            type: string
          agentName:
            description: Name of the enterprise agent generating usage.
            type: string
          enterpriseUnitsUsed:
            description: Number of enterprise agent units owned by the specific account
              group in the usage period.
            format: int64
            type: integer
          enterpriseUnitsProjected:
            description: "Number of enterprise units projected in the current usage\
              \ period, based on units consumed to date and configuration of enabled\
              \ tests. This value is updated hourly. Returns non-zero value only for\
              \ organizations with metered billing."
            format: int64
            type: integer
          vagentId:
            description: Unique identifier of the virtual agent generating usage
            type: string
        type: object
      example:
      - aid: "7625"
        agentId: "121404"
        accountGroupName: Support
        agentName: TEVA-test-agent
        enterpriseUnitsUsed: 599878
        enterpriseUnitsProjected: 597808
        vagentId: "123456"
      - aid: "315"
        agentId: "121404"
        accountGroupName: Documentation
        agentName: lab-physical-appliance-1
        enterpriseUnitsUsed: 597123
        enterpriseUnitsProjected: 597808
        vagentId: "789"
    Tests_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: Unique identifier of the account group which owns the test.
          accountGroupName:
            description: Name of the account group which owns the test.
          testId:
            description: Unique identifier of the test generating usage.
            type: string
          testName:
            description: Name of the test generating usage.
            type: string
          testType:
            description: The type of test that generated the usage data. Note that
              this parameter provides a user-friendly description of the test type
              and should not be parsed to determine the endpoint for querying configuration
              details.
            type: string
          cloudUnitsUsed:
            description: Number of cloud units that the test has consumed in the usage
              period.
            format: int64
            type: integer
          cloudUnitsProjected:
            description: "The estimated number of cloud units that the test is expected\
              \ to consume during the usage period. This estimate is determined by\
              \ considering the units consumed up to the current time and the test's\
              \ configuration. It's important to note that this value is updated every\
              \ hour. For new tests, the `cloudUnitsProjected` parameter is absent\
              \ until the projection is calculated."
            format: int64
            type: integer
        type: object
    EndpointAgents_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: Unique identifier of the account group owning the endpoint
              agents.
          accountGroupName:
            description: Name of the account group which owns the endpoint agents.
          endpointAgentsUsed:
            description: Number of endpoint agents owned by the specific account group
              in the usage period.
            format: int64
            type: integer
        type: object
    EndpointAgentsEssentials_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: Unique identifier of the account group owning the endpoint
              agents essentials.
          accountGroupName:
            description: Name of the account group which owns the endpoint agents
              essentials.
          endpointAgentsEssentialsUsed:
            description: Number of endpoint agents essentials owned by the specific
              account group in the usage period.
            format: int64
            type: integer
        type: object
    EndpointAgentsEmbedded_inner:
      allOf:
      - $ref: '#/components/schemas/AccountGroup'
      - properties:
          aid:
            description: Unique identifier of the account group that owns the embedded
              endpoint agents.
          accountGroupName:
            description: Name of the account group that owns the embedded endpoint
              agents.
          endpointAgentsEmbeddedUsed:
            description: Number of endpoint agents embedded owned by the specific
              account group in the usage period.
            format: int64
            type: integer
        type: object
    OrganizationsQuotasAssign_organizations_inner:
      example:
        orgId: "315"
        accountGroups:
        - value: 12000
          aid: "35"
        - value: 12000
          aid: "35"
      properties:
        orgId:
          description: Unique identifier of the organization.
          example: "315"
          type: string
        accountGroups:
          description: List of account groups quotas.
          items:
            $ref: '#/components/schemas/AccountGroupQuota'
          type: array
      type: object
    OrganizationsQuotasUnassign_organizations_inner:
      example:
        orgId: "315"
        accountGroups:
        - "35"
        - "720"
      properties:
        orgId:
          description: Unique identifier of the organization.
          example: "315"
          type: string
        accountGroups:
          description: List of account group IDs.
          example:
          - "35"
          - "720"
          items:
            type: string
          type: array
      type: object
    SelfLinks__links:
      description: A links object containing the self link.
      properties:
        self:
          $ref: '#/components/schemas/Link'
      readOnly: true
      type: object
  securitySchemes:
    BearerAuth:
      description: Bearer authentication token
      scheme: bearer
      type: http

